services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intranet_produccion_web
    restart: unless-stopped
    expose:
      - "3200"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - intranet_produccion_web_network
    volumes:
      - /home/ec2-user/.aws:/root/.aws:ro

networks:
  intranet_produccion_web_network:
    external: true